[dependencies]
repos = [
    ["balticasystems", "csr.h"],
    ["balticasystems", "extensions.h"],
    ["balticasystems", "qemu.h"],
    ["balticasystems", "Makefile"],
    ["balticasystems", "emilia.ld"],
    ["balticasystems", "jny.ld"],
    ["balticasystems", "jny"],
]
